version: "3.8" # Specifies the version of the Docker Compose file format
services:
  dashdot:
    image: mauricenino/dashdot # Image to be used for this service
    ports:
      - 3003:3001 # Port 3003 on the host is mapped to port 3001 in the container
    volumes:
      - /:/mnt/host:ro # Mounts the root directory of the host as read-only at /mnt/host in the container
    privileged: true # Runs the container in privileged mode, allowing it access to host devices
    restart: unless-stopped
networks: {}