name: portainer
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - mode: ingress
        target: 9000
        published: "9000"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /YOUR/DATA/DIRECTORY
        target: /data
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    command: []
    environment: []
    networks:
      - default
    privileged: false
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7915M
networks:
  default:
    name: portainer_default
x-casaos:
  hostname: ""
  scheme: http
  index: /
  port_map: ""
  author: self
  category: self
  icon: https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_200,h_200/https://api.charmhub.io/api/v1/media/download/charm_cMu7M9K6a65FsKZvrLZOZwyQradwbs7E_icon_5cef79c2d18f67464f39c8f2cf2d7ebb815b0071f04d3ffbb94f49fddd3ab666.png
  title:
    custom: Portainer
version: "3.8"
